### ISSUE TITLE
links in the readme are broken 

### ISSUE THREAD

**Issue by lebed2045** [euler-xyz/euler-contracts#180]
Docs
[General Euler Docs](https://docs.euler.finance/)
[Contract Architecture](https://docs.euler.finance/developers/architecture)
[Contract Reference](https://docs.euler.finance/developers/contract-reference)
[IEuler.sol Solidity Interface](https://github.com/euler-xyz/euler-interfaces/blob/master/IEuler.sol)

**Comment by hoytech** [comment]
Thank you! Sorry for the delay. @TanyaRoze fixed this in the following PR:

https://github.com/euler-xyz/euler-contracts/pull/187
