### ISSUE TITLE
Flaky tests failing with `Error: equals failure: x was not y +/- z`

### ISSUE THREAD

**Issue by cameel** [euler-xyz/euler-contracts#93]
I'm seeing some tests fail randomly from time to time. It seems that they might not be deterministic enough or there could be a bug:

https://app.circleci.com/pipelines/github/ethereum/solidity/21640/workflows/e8f4e019-264e-4572-bab7-177ef32c5c6a/jobs/948090
```
  297 passing (11m)
  1 failing

  1) reserves
       reserves:
     Error: equals failure: 0.000000013484437479 was not 0.000000015 +/- 0.000000001
      at equals (test/lib/eTestLib.js:1150:19)
      at TestSet._runTest (test/lib/eTestLib.js:912:17)
      at Context.<anonymous> (test/lib/eTestLib.js:851:21
```
https://app.circleci.com/pipelines/github/ethereum/solidity/21639/workflows/be150d7f-d0b1-4730-a26f-e6a5a4316fe7/jobs/948031
```
297 passing (7m)
  1 failing

  1) transfer dTokens
       lower decimals:
     Error: equals failure: 0.000000008000000102 was not 0.000000008 +/- 0.0000000000000001
      at equals (test/lib/eTestLib.js:1150:19)
      at TestSet._runTest (test/lib/eTestLib.js:912:17)
      at Context.<anonymous> (test/lib/eTestLib.js:851:21)

```

I'm actually compiling contracts with the latest compiler (the whole point for me is to test the compiler) and adjusting optimizer settings, which could theoretically be the cause but most of the time all tests pass so I think that's unlikely. I think that a problem is probably in the tests.

**Comment by hoytech** [comment]
Thanks for the report! I'm guessing that there is an incorrect assumption about the passage of time in that test, causing it to be non-deterministic. We'll look into it ASAP.

**Comment by hoytech** [comment]
I added a new feature to the test library: `TEST_SLEEP`. If this env variable is set it will artificially slow down all operations, to help identify tests that have non-deterministic time dependencies. In addition to the two mentioned in this issue, I also found two more tests.

The fixes are available in this PR, which we'll merge very soon: https://github.com/euler-xyz/euler-contracts/pull/94

**Comment by hoytech** [comment]
... and merged. Please let us know if you see any more problems, and thanks again!

**Comment by cameel** [comment]
Thanks! Haven't seen any more failures so far. If there are any I'll try the new option and report back.
