### ISSUE TITLE
Flaky test for EUL distributor: `expected 'incorrect data length (argument=null,…' to include 'proof invalid/expired'`

### ISSUE THREAD

**Issue by cameel** [euler-xyz/euler-contracts#99]
This test failed today in [968204](https://app.circleci.com/pipelines/github/ethereum/solidity/22072/workflows/91176ebc-3a39-403e-9de1-3c1b9894f3cf/jobs/968204):
```
309 passing (9m)
  1 failing

  1) EUL distributor
       invalid claim inputs:
     AssertionError: expected 'incorrect data length (argument=null,…' to include 'proof invalid/expired'
      at Object.cb (test/eulDistributor.js:266:42)
      at TestSet._runAction (test/lib/eTestLib.js:1051:13)
      at TestSet._runTest (test/lib/eTestLib.js:904:26)
      at Context.<anonymous> (test/lib/eTestLib.js:878:21)
```
I have only seen it fail once so far and after rerunning ([968410](https://app.circleci.com/pipelines/github/ethereum/solidity/22072/workflows/79837310-bace-4c50-9bf2-2f62ce524836/jobs/968410)) it passed.

**Comment by hoytech** [comment]
Thanks for the reports! We're looking into them now.

**Comment by cameel** [comment]
Great! By the way, this one appeared a few more times today so it was not just a one-off.

**Comment by kasperpawlowski** [comment]
It seems that the negative test case is not deterministic. Fixing it. Thanks for reporting!

**Comment by cameel** [comment]
Thanks! I'm going to close it then.
